export const INCREMENT_USERINFO = "INCREMENT_USERINFO";
export type INCREMENT_USERINFO = typeof INCREMENT_USERINFO;

export const DECREMENT_USERINFO = "DECREMENT_USERINFO";
export type DECREMENT_USERINFO = typeof DECREMENT_USERINFO;